name = "autor-dev-pkg-checkout"
main = "app/page.tsx"
compatibility_date = "2024-05-01"

[build]
command = "npm run build"
upload_dir = ".next/static"

[env.production]
STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "checkout-ui-app"

[site]
bucket = ".next/static"

[triggers]
crons = ["0 0 * * *"]
